### ISSUE TITLE
Feat : 🆙 Bump Ditto to v.0.7.0

### ISSUE THREAD

**Issue by Tbelleng** [KasarLabs/ditto#54]
# Changelog for Upcoming Release
Here is a list of all changelog from last v0.5.1 to 0.7.0.1 Starknet-spec version : 

### New Features and Improvements
- [x] Add v3 transactions additional fields (PR #162)
- [x] Bound numeric properties by FELT and make builtin resources optional (PR #164)
- [x] Add the segment arena builtin (PR #165)
- [x] Add stricter restrictions on v3 fields (PR #169)
- [x] Refactor traceTransactions and estimateFee, and rename STRK to FRI (https://github.com/starkware-libs/starknet-specs/pull/174)
- [x] Use the name FRI for STRK, added TRANSACTION_EXECUTION_ERROR, added the SKIP_VALIDATE flag to starknet_estimateFee, clarified semantics of simulate and estimate (PR #175, #177)
- [x] Add units to FEE_ESTIMATE (PR #175)
- [x] Add data consumption to receipts and traces, add EIP-4844 related fields, add getBlockWithReceipts method (PR #187, #188, #189, #191)
- [x] Spec organization: Introduce TXN_RECEIPT_WITH_BLOCK_INFO and remove the pending receipts objects (PR #195)
- [x] Import BROADCASTED_DECLARE_TXN in write API (PR #178)
- [x] Add string data to VALIDATION_FAILURE (PR #179)
- [x] Change execution resource counters to integers (PR #147)
- [x] Allow EMITTED_EVENT to contain events from the pending block (PR #151)
- [x] Disallow block_hash/block_number/new_root in the PENDING_BLOCK_HEADER schema (PR #154)
- [x] Introduce v3 transactions (PR #149)
- [x] Add state_diff to L1_HANDLER and DELEGATE call type, add resources to internal calls within a trace (PR #160, #161)
- [x] Bump version to 0.7.1 (PR #202)

### Fixes
- [x] Fix DECLARE_TXN_V1 version (PR #170)
- [x] Make trace fields optional (as in 0.5.1) (PR #172)
- [x] Typo fix and added property to schema object (PR #173)
- [x] Fix: change l1_handler version to enum, make data_gas related fields required in the block header, add 4844-related fields to the pending block header (PR #190, #193, #194)
- [x] Fix: make revert_reason required in reverted transaction traces, fix storage key pattern, add a comment explaining the execution_resources property name, add execution resources to l1 handler traces (PR #197, #198, #199, #200, #201)
